/*
 * Copyright 2017 José A. Pacheco Ondoño - joanpaon@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.japo.java.views;

import java.awt.Color;
import java.util.Properties;
import org.japo.java.controllers.Controller;
import org.japo.java.libraries.UtilesApp;
import org.japo.java.libraries.UtilesValidacion;
import org.japo.java.models.Model;

/**
 *
 * @author José A. Pacheco Ondoño - joanpaon@gmail.com
 */
public class View extends javax.swing.JFrame {

    // Fichero Propiedades
    public static final String FICHERO = "view.properties";

    // Referencias
    private Model model;
    private Controller control;
    private Properties prpView;

    // Constructor
    public View() {
        // Inicializacion Anterior
        initBefore();

        // Creación Vista
        initComponents();

        // Inicializacion Posterior
        initAfter();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        txfNumero = new javax.swing.JTextField();
        lblSerie = new javax.swing.JLabel();
        txfSerie = new javax.swing.JTextField();
        lblFraccion = new javax.swing.JLabel();
        cbbFraccion = new javax.swing.JComboBox();
        lblFecha = new javax.swing.JLabel();
        txfFecha = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txfPrecio = new javax.swing.JTextField();
        pnlControl = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lotería Nacional");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 12), java.awt.Color.blue)); // NOI18N

        lblNumero.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblNumero.setText("Número");

        txfNumero.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txfNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfNumero.setText("00000");
        txfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfNumeroFocusLost(evt);
            }
        });

        lblSerie.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblSerie.setText("Serie");

        txfSerie.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txfSerie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfSerie.setText("000");
        txfSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfSerieFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfSerieFocusLost(evt);
            }
        });

        lblFraccion.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblFraccion.setText("Fracción");

        cbbFraccion.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        cbbFraccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        lblFecha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblFecha.setText("Fecha");

        txfFecha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txfFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfFecha.setText("01/01/1970");
        txfFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfFechaFocusLost(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblPrecio.setText("Precio");

        txfPrecio.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txfPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfPrecio.setText("20.00");
        txfPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfPrecioFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addGap(18, 18, 18)
                        .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(txfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblSerie)
                        .addGap(18, 18, 18)
                        .addComponent(txfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblFraccion)
                        .addGap(18, 18, 18)
                        .addComponent(cbbFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbFraccion, lblFecha, lblFraccion, lblNumero, lblPrecio, lblSerie, txfFecha, txfNumero, txfPrecio, txfSerie});

        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerie)
                    .addComponent(txfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFraccion)
                    .addComponent(cbbFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(txfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbFraccion, lblFecha, lblFraccion, lblNumero, lblPrecio, lblSerie, txfFecha, txfNumero, txfPrecio, txfSerie});

        pnlControl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 12), java.awt.Color.blue)); // NOI18N

        btnImportar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.setPreferredSize(new java.awt.Dimension(106, 30));
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportar)
                .addGap(20, 20, 20))
        );

        pnlControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExportar, btnImportar});

        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlControlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExportar, btnImportar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        control.procesarImportacion(evt);
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        control.procesarExportacion(evt);
    }//GEN-LAST:event_btnExportarActionPerformed

    private void txfNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNumeroFocusGained
        txfNumero.setForeground(Color.BLACK);
        txfNumero.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfNumeroFocusGained

    private void txfSerieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfSerieFocusGained
        txfSerie.setForeground(Color.BLACK);
        txfSerie.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfSerieFocusGained

    private void txfFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfFechaFocusGained
        txfFecha.setForeground(Color.BLACK);
        txfFecha.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfFechaFocusGained

    private void txfPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPrecioFocusGained
        txfPrecio.setForeground(Color.BLACK);
        txfPrecio.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfPrecioFocusGained

    private void txfNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfNumeroFocusLost
        txfNumero.setBackground(Color.WHITE);
        UtilesValidacion.validarCampoTexto(txfNumero, Model.ER_NUMERO, "*");
    }//GEN-LAST:event_txfNumeroFocusLost

    private void txfSerieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfSerieFocusLost
        txfSerie.setBackground(Color.WHITE);
        UtilesValidacion.validarCampoTexto(txfSerie, Model.ER_SERIE, "*");
    }//GEN-LAST:event_txfSerieFocusLost

    private void txfFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfFechaFocusLost
        txfFecha.setBackground(Color.WHITE);
        UtilesValidacion.validarCampoFecha(txfFecha, "*");
    }//GEN-LAST:event_txfFechaFocusLost

    private void txfPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPrecioFocusLost
        txfPrecio.setBackground(Color.WHITE);
        UtilesValidacion.validarCampoTexto(txfPrecio, Model.ER_PRECIO, "*");
    }//GEN-LAST:event_txfPrecioFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        control.procesarCierreVista(evt);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    public javax.swing.JComboBox cbbFraccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFraccion;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlDatos;
    public javax.swing.JTextField txfFecha;
    public javax.swing.JTextField txfNumero;
    public javax.swing.JTextField txfPrecio;
    public javax.swing.JTextField txfSerie;
    // End of variables declaration//GEN-END:variables

    // Inicializacion Anterior
    private void initBefore() {
        // Crear Modelo
        model = new Model();

        // Crear Controlador
        control = new Controller(model, this);

        // Cargar Propiedades Vista
        prpView = UtilesApp.cargarPropiedades(FICHERO);

        // Restaurar Estado
        control.restaurarEstadoVista(this, prpView);

        // Otras inicializaciones
    }

    // Inicializacion Posterior
    private void initAfter() {
        // Modelo > Vista
        control.sincronizarModeloVista(model, this);

        // Enfocar Control Inicial
        btnImportar.requestFocus();

        // Otras inicializaciones
    }
}
